### ISSUE TITLE
Logs should be captured (so kube doesn't lose them) when the job is done

### ISSUE THREAD

**Issue by ihodes** [hammerlab/coclobas#111]

**Comment by smondet** [comment]
W already do that: https://github.com/hammerlab/coclobas/blob/780c6d63ff683a12ccf749ae2ec5986abe9292e0/src/lib/server.ml#L259-L264

But it seems sometimes kubernertes does not have the logs *ever*?

**Comment by ihodes** [comment]
When is a job in the Remove state? If we were to try to grab the logs at every state, would we be more likely to get them?

**Comment by smondet** [comment]
`` `Remove`` (form the list of active/interesting stuff) is the last action, after finishing, it's just above: https://github.com/hammerlab/coclobas/blob/master/src/lib/server.ml#L225-L229

I don't know if constantly saving logs and description would do anything better but we can try, is you case an error "logs not found" (Ketrew UI is red-ish) or a case of `kubectl logs` returning `0` with no content (ketrew UI is green-ish)?

On the GKE, we have the problem of the SSH-Keys, on top of kubernetes weirdness, if when the jobs is running/finishing the GCloud-metadata is topped then Coclobas cannot get the logs, then some adminus-ex-machina deletes ssh-keys to make space, but by the time it has propagated to the nodes, the job long dead and forgotten by kubernetes.
Really no idea how to fix that.

**Comment by ihodes** [comment]
> I don't know if constantly saving logs and description would do anything better but we can try, is you case an error "logs not found" (Ketrew UI is red-ish) or a case of kubectl logs returning 0 with no content (ketrew UI is green-ish but there is no output)?

For this one, it was the "blank logs" situation (not a Ketrew red UI thing).

Yeah, I agree; it's not something we can really solve with such unreliable underpinnings, unfortunately...

**Comment by smondet** [comment]
> For this one, it was the "blank logs" situation (not a Ketrew red UI thing).

So it means that Coclobas managed to “call” kubernetes at least once and never got any output (we always keeps the longest output
https://github.com/hammerlab/coclobas/blob/master/src/lib/kube_job.ml#L190).
This indistinguishable from a genuine job that has no output.

**Comment by ihodes** [comment]
It could have either

1. called it before there were logs, and then never again (unlikely,
looking at how the code is structured)
2. called it after kube had already lost the logs?

I don't think there's really a 100% working solution to this, but calling
logs more often might help us approach the limits of the bugginess we're
stuck with here.

**Comment by smondet** [comment]
Closing in favor of #112
