### ISSUE TITLE
Ketrew-plugin: should not store job-id

### ISSUE THREAD

**Issue by smondet** [hammerlab/coclobas#17]
Right now it's there:
https://github.com/hammerlab/coclobas/blob/add-loop-backoff/src/ketrew_backend/plugin.ml#L10

so it make the jobs not “restartable" (tries to re-run with same ID).

**Comment by ihodes** [comment]
Could make things simpler overall if Coclobas server is in charge of IDs instead of the client.

**Comment by smondet** [comment]
@ihodes yes maybe, still undecided
