### ISSUE TITLE
Losing logs

### ISSUE THREAD

**Issue by ihodes** [hammerlab/coclobas#56]
![](http://link.isaachodes.io/131Q1D0V1x1E/Screen%20Shot%202016-09-30%20at%205.11.53%20PM.png) 

This used to be a huge logfile; seen this a few times now, somehow the logs disappear. Kubectl logs also report nothing, later.

**Comment by smondet** [comment]
Is it the case we checked off-line where `kubectl logs` returns an empty log but still returns 0?

**Comment by ihodes** [comment]
Yes exactly (and it seems to return the correct logs first, and then lose them).

**Comment by smondet** [comment]
OK, this one is the issue that we could hack-around by remembering the largest log output instead of the latest log output.

**Comment by ihodes** [comment]
I like that idea!

**Comment by smondet** [comment]
Issue worked around in #71.
