### ISSUE TITLE
Consider new DB 

### ISSUE THREAD

**Issue by ihodes** [hammerlab/coclobas#60]
`git cloning` a DB that had some (less than 50) 5kish node jobs submitted to it doesn't seem to work, so there's no way to interact with the DB without the client itself. 

Is there a lot that Irmin buys us? 

Just opening a conversation here about the issue. as we've talked a bit offline in the past but should record this dialogue somewhere.

**Comment by ihodes** [comment]
Another unexpected downside is that trying to remove a coclobas install involves `rm -rf`ing a rather complex directory structure (Irmin's .git), which can be quite slow.

**Comment by smondet** [comment]
We can just try to apply the Irmin functor to something else while in production; I picked Git because it's the coolest :)

**Comment by ihodes** [comment]
Oh nice, didn't realize we had other options; would definitely be good to do!

**Comment by smondet** [comment]
See the list of backends:
<https://github.com/mirage/irmin#backends>

I tried to run the tests with git and with:

```ocaml
module Store =
  Irmin_unix.Irmin_fs.Make
    (Irmin.Contents.String)
    (Irmin.Ref.String)
    (Irmin.Hash.SHA1)
```

I got exactly same number of Inodes: 318 (but the FS layout is indeed different,
Irmin's own one is seems more “readable” by itself).

Then I tried this:
<http://linuxsagas.digitaleagle.net/2013/03/21/too-many-inodes/>

```
 $ git gc  --aggressive
Counting objects: 177, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (157/157), done.
Writing objects: 100% (177/177), done.
Total 177 (delta 69), reused 108 (delta 0)

 $ du -sh --inodes
18    
```

so periodic garbage collection of the Git bare-repository seems to be very
efficient at reducing the inode-count.

**Comment by armish** [comment]
Is there a reason why we are not using the `irmin.mem` option?

**Comment by smondet** [comment]
@armish in the general case, we want to be able to keep going after restarts right?
We indeed could use the `irmin.mem` backend in some settings (like in `epidisco` where we see the whole setup as "disposable").

**Comment by armish** [comment]
@smondet: that would be awesome! Especially if it is optional and there are ways to switch strategies in case needed.

Also thanks for the git cleaning up tip. I will use that to temporarily work-around my issues.

**Comment by smondet** [comment]
Using Trakeva (hence sqlite or postgresql) now.
