### ISSUE TITLE
`kubectl create -f` failing intermitantly 

### ISSUE THREAD

**Issue by ihodes** [hammerlab/coclobas#62]
> Reason: "Error-from-coclobas: Starting failed: Shell-command failed:\nCommand:\n```\nkubectl create -f /tmp/coclojob84240d.json\n```\nStatus: Exited with 1\n\nStandard-output: empty.\n\nStandard-error:\n```\nThe connection to the server 104.196.31.136 was refused - did you specify the right host or port?\n```\n"

**Comment by smondet** [comment]
Google's Kube deployment must be pretty weak.

We need to do the same dance as we do in the `` `Update _`` case for the `` `Start _`` case.

**Comment by ihodes** [comment]
Yeah it's surprisingly flaky, it seems, need to retry everywhere
