### ISSUE TITLE
Should job be in Still/started_running state if it's "pending"?

### ISSUE THREAD

**Issue by ihodes** [hammerlab/coclobas#67]
Curiously, the logs call returns (no output, but it's green http://link.isaachodes.io/3A0V472e1M1R/Screen%20Shot%202016-10-18%20at%202.28.29%20AM.png)

Pending: http://link.isaachodes.io/370S3s0b1z00/Screen%20Shot%202016-10-18%20at%202.28.44%20AM.png

**Comment by smondet** [comment]
Yes when a job is Pending for kubernetes it means it has been submitted so for Ketrew's point of view it has been started (it's the same for all schedulers).

**Comment by smondet** [comment]
and yes i've noticied sometimes `kubectl logs` returns 0 when there are no logs; when that happens, there is no way to distinguish between "empty logs" and "no logs."

**Comment by ihodes** [comment]
Do we have a solution for this?

**Comment by smondet** [comment]
@ihodes 

- the `running/sill_running` part, no that's normal
- for the empty logs; not really? Kubernetes sends something "as valid" we should trust it, right?
    - we could consider that logs should be always growing and warn if they don't, that'd be hacky-work-around?
    - It's still not the case in your example above, the job was pending so didn't have logs.
