### ISSUE TITLE
Document what coclobas does

### ISSUE THREAD

**Issue by ihodes** [hammerlab/coclobas#77]
1. OCaml interface to Google's Kube (ideally, more, eventually)
2. HTTP server and CLI client for scheduling kube jobs
3. Keeps logs (that Kube loses)
4. Throttles submission to keep Kube from crashing
5. … what else does it "fix" about plain Kube?

**Comment by smondet** [comment]
It's maybe part of (1) but there is also the fact simplifying the use of secrets to pass a script to run (instead of a command), and the use of arbitrary NFS mounts (and other "secrets").

**Comment by smondet** [comment]
It's also gentle with Kube by allowing `n` random failures before declaring a job dead.

**Comment by smondet** [comment]
It starts/checks-on/stops  GCloud-kube-clusters.
